language: node_js
node_js:
  - 0.12
  - 4
  - 6
before_script: >
  if nvm ls-remote --lts | grep "$(nvm current)"; then
    echo "running on a LTS node version, linting"
    npm run lint
  else
    echo "running on a non-LTS node version, skipping linting"
  fi
script:
  - npm run coverage
after_success:
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls
